export const countrylist = [
  {
    name: 'Afghanistan (‫افغانستان‬‎)',
    iso2: 'af',
    dialCode: '93',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Australia',
    iso2: 'au',
    dialCode: '61',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Bahrain (‫البحرين‬‎)',
    iso2: 'bh',
    dialCode: '973',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Bangladesh (বাংলাদেশ)',
    iso2: 'bd',
    dialCode: '880',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Bhutan (འབྲུག)',
    iso2: 'bt',
    dialCode: '975',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Canada',
    iso2: 'ca',
    dialCode: '1',
    priority: 1,
    areaCodes: null,
  },
  {
    name: 'China (中国)',
    iso2: 'cn',
    dialCode: '86',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Denmark (Danmark)',
    iso2: 'dk',
    dialCode: '45',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Egypt (‫مصر‬‎)',
    iso2: 'eg',
    dialCode: '20',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'France',
    iso2: 'fr',
    dialCode: '33',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Germany (Deutschland)',
    iso2: 'de',
    dialCode: '49',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Hong Kong (香港)',
    iso2: 'hk',
    dialCode: '852',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Iceland (Ísland)',
    iso2: 'is',
    dialCode: '354',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'India (भारत)',
    iso2: 'in',
    dialCode: '91',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Indonesia',
    iso2: 'id',
    dialCode: '62',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Israel (‫ישראל‬‎)',
    iso2: 'il',
    dialCode: '972',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Italy (Italia)',
    iso2: 'it',
    dialCode: '39',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Kuwait (‫الكويت‬‎)',
    iso2: 'kw',
    dialCode: '965',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Malaysia',
    iso2: 'my',
    dialCode: '60',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Maldives',
    iso2: 'mv',
    dialCode: '960',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Nepal (नेपाल)',
    iso2: 'np',
    dialCode: '977',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Russia (Россия)',
    iso2: 'ru',
    dialCode: '7',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Saudi Arabia (‫المملكة العربية السعودية‬‎)',
    iso2: 'sa',
    dialCode: '966',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Singapore',
    iso2: 'sg',
    dialCode: '65',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'South Africa',
    iso2: 'za',
    dialCode: '27',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Sri Lanka (ශ්‍රී ලංකාව)',
    iso2: 'lk',
    dialCode: '94',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'Thailand (ไทย)',
    iso2: 'th',
    dialCode: '66',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)',
    iso2: 'ae',
    dialCode: '971',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'United Kingdom',
    iso2: 'gb',
    dialCode: '44',
    priority: 0,
    areaCodes: null,
  },
  {
    name: 'United States',
    iso2: 'us',
    dialCode: '1',
    priority: 0,
    areaCodes: null,
  },
];

export const types = [
  {
    name: 'Tables',
    value: 0,
  },
  {
    name: 'Chairs',
    value: 1,
  },
  {
    name: 'Tables',
    value: 2,
  },
  {
    name: 'Appliances',
    value: 3,
  },
  {
    name: 'Sofas',
    value: 4,
  },
  {
    name: 'Beds',
    value: 5,
  },
];
